name: kiralik_kaleci
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  google_sign_in: ^6.1.6
  cloud_firestore: ^5.6.0
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  persistent_bottom_nav_bar: ^6.2.1
  bottom_navy_bar: ^6.0.0
  toggle_switch: ^2.1.0
  #flutter_credit_card: ^4.0.1
  workmanager: ^0.5.2
  image_picker: ^1.0.7
  another_carousel_pro: ^1.0.2
  carousel_slider: ^5.0.0
  dart_date: ^1.3.2
  firebase_storage: ^12.3.7
  dropdown_textfield: ^1.0.8
  flutter_chat_ui: ^1.6.12
  district_picker_turkey_map: ^0.1.10
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  flutter_email_sender: ^6.0.3
  path_provider: ^2.0.15
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  leak_tracker: 10.0.7

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/icons/
    - lib/images/credit_card_background.jpg
    - lib/images/image1.jpg