// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsR90X4XH0-YUBOxwRzs7GpR5LX9C4frc',
    appId: '1:783910203845:web:ea4db62933dbf55fc2dbac',
    messagingSenderId: '783910203845',
    projectId: 'kiralikkaleci-21f26',
    authDomain: 'kiralikkaleci-21f26.firebaseapp.com',
    storageBucket: 'kiralikkaleci-21f26.appspot.com',
    measurementId: 'G-TK1S0WGYRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdbnLqEXRI_7etAi7ZsC1HrBsx5Shb2U',
    appId: '1:783910203845:android:1bdba6ea005701d2c2dbac',
    messagingSenderId: '783910203845',
    projectId: 'kiralikkaleci-21f26',
    storageBucket: 'kiralikkaleci-21f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLXljabFo3SnF-EGffcy-iBHr2UY1xong',
    appId: '1:783910203845:ios:440c37bb590a52fdc2dbac',
    messagingSenderId: '783910203845',
    projectId: 'kiralikkaleci-21f26',
    storageBucket: 'kiralikkaleci-21f26.appspot.com',
    iosBundleId: 'com.example.kiralikKaleci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLXljabFo3SnF-EGffcy-iBHr2UY1xong',
    appId: '1:783910203845:ios:440c37bb590a52fdc2dbac',
    messagingSenderId: '783910203845',
    projectId: 'kiralikkaleci-21f26',
    storageBucket: 'kiralikkaleci-21f26.appspot.com',
    iosBundleId: 'com.example.kiralikKaleci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsR90X4XH0-YUBOxwRzs7GpR5LX9C4frc',
    appId: '1:783910203845:web:8575fae1a2e08b27c2dbac',
    messagingSenderId: '783910203845',
    projectId: 'kiralikkaleci-21f26',
    authDomain: 'kiralikkaleci-21f26.firebaseapp.com',
    storageBucket: 'kiralikkaleci-21f26.appspot.com',
    measurementId: 'G-V476KEK6WY',
  );

}